Add authorized recipe controller
COP4331-LargeGroupProject-Fall22/backend pull request #95
Opened 2022-11-19 01:16 UTC by mplekunov

2022-11-19 11:30 UTC, mplekunov commented
The recipe routes have been rewritten to fit our new specifications:
Routes differentiate between two cases: Unauthorized && Authorized users.
 
Unauthorized case happens when request doesn't include "Authorization" header.
Authorized case happens when request includes "Authorization" header.

When user is Authorized. Responses (in both get/getAll calls) will contain additional field "isFavorite". When it's set to true, it means this recipe is part of the favorite recipes list of the user and vice versa.

2022-11-23 18:43 UTC, nashirj commented
Pls fix merge conflicts

2022-11-26 18:01 UTC, nashirj requested changes

2022-11-26 18:01 UTC, nashirj commented on server/serverAPI/controller/AuthorizedRecipeController.ts
> +    protected async convertToUserRecipe(recipe: IRecipe, req: Request, res: Response): Promise<UserRecipe> {
Can you update this and below to have logic for allergens as well please

2022-11-26 18:01 UTC, nashirj commented on server/serverAPI/model/recipe/UserBaseRecipe.ts
> +    constructor(recipe: IBaseRecipe, isFavorite: boolean) {
Please add `hasAllergen`

2022-11-26 18:01 UTC, nashirj commented
Overall looks good, just pls add logic for hasAllergen

2022-11-30 23:20 UTC, closed without merging